name: HTML Deployment CI/CD

on:
  push:
    branches: ["master","develop"]
  pull_request:
    branches: ["master","develop"]
  workflow_dispatch: #run the manual workflow

jobs:
  deploy-test:
    name: Deploy in TEST
    runs-on: ubuntu-latest
    environment: test

    steps:
      - uses: actions/checkout@v2
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: |
            **/.git*
            **/.git*/**
            
  deploy-prod:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest
    environment: prod
    needs: deploy-test

    steps:
      - uses: actions/checkout@v2
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: |
            **/.git*
            **/.git*/**
